# Generated by Django 4.1.5 on 2023-02-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='password',
        ),
        migrations.AlterField(
            model_name='adduser',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiter.country'),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiter.authuser'),
        ),
    ]
